#pragma once

#define MATRIX_ROWS 4
#define MATRIX_COLS 4

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP6
#define I2C1_SCL_PIN GP7

#define OLED_DISPLAY_ADDRESS 0x3C
#define DEBOUNCE 5
