MCU = RP2040
BOOTLOADER = rp2040

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no

EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
