# Copyright 2024 Hackpad
# SPDX-License-Identifier: GPL-2.0-or-later

MCU = RP2040
BOOTLOADER = rp2040

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
NKRO_ENABLE = yes
BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes

MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
BACKLIGHT_ENABLE = no
ENCODER_ENABLE = no

I2C_DRIVER_REQUIRED = yes
